// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBOUEbl6VPIrgoWMuFI3SxwbA2282VNQA',
    appId: '1:821257436588:web:6846e22a7c831adae44e09',
    messagingSenderId: '821257436588',
    projectId: 'fittrackpro-2abbe',
    authDomain: 'fittrackpro-2abbe.firebaseapp.com',
    storageBucket: 'fittrackpro-2abbe.firebasestorage.app',
    measurementId: 'G-31KEE0PBYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcVJzT9zltqc1ruZQr11PLKs3RkYqoS3Y',
    appId: '1:821257436588:android:569b536890504aa2e44e09',
    messagingSenderId: '821257436588',
    projectId: 'fittrackpro-2abbe',
    storageBucket: 'fittrackpro-2abbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnYpgEcmx2ih9EV3nRGSVw5sraUbWSpqw',
    appId: '1:821257436588:ios:a2cd8c65e721d32ae44e09',
    messagingSenderId: '821257436588',
    projectId: 'fittrackpro-2abbe',
    storageBucket: 'fittrackpro-2abbe.firebasestorage.app',
    iosClientId: '821257436588-aqjs42c5f9o3si7jl8jan67lfcbpc6uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitTrackPro2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnYpgEcmx2ih9EV3nRGSVw5sraUbWSpqw',
    appId: '1:821257436588:ios:e5d64e9894c002cee44e09',
    messagingSenderId: '821257436588',
    projectId: 'fittrackpro-2abbe',
    storageBucket: 'fittrackpro-2abbe.firebasestorage.app',
    iosClientId: '821257436588-uprk0hgn3klsr24ua3pu718sb93u2r1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitTrackPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBOUEbl6VPIrgoWMuFI3SxwbA2282VNQA',
    appId: '1:821257436588:web:34fa3fe6eda6dc05e44e09',
    messagingSenderId: '821257436588',
    projectId: 'fittrackpro-2abbe',
    authDomain: 'fittrackpro-2abbe.firebaseapp.com',
    storageBucket: 'fittrackpro-2abbe.firebasestorage.app',
    measurementId: 'G-S4WYTPK246',
  );
}
